//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template.CrossCutting.Resources.ExtensionMethods {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Constants() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrossCutting.Resources.ExtensionMethods.Constants", typeof(Constants).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to EXC_EMPTY_LIST.
        /// </summary>
        public static string COD_EMPTY_LIST {
            get {
                return ResourceManager.GetString("COD_EMPTY_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to EXC_FALSE_VALUE.
        /// </summary>
        public static string COD_FALSE_VALUE {
            get {
                return ResourceManager.GetString("COD_FALSE_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to EXC_HAS_NULL_OBJECT.
        /// </summary>
        public static string COD_HAS_NULL_OBJECT {
            get {
                return ResourceManager.GetString("COD_HAS_NULL_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to EXC_LIST_NULL_OR_EMPTY.
        /// </summary>
        public static string COD_LIST_NULL_OR_EMPTY {
            get {
                return ResourceManager.GetString("COD_LIST_NULL_OR_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to EXC_NOT_NULL_OBJECT.
        /// </summary>
        public static string COD_NOT_NULL_OBJECT {
            get {
                return ResourceManager.GetString("COD_NOT_NULL_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to EXC_NULL_OBJECT.
        /// </summary>
        public static string COD_NULL_OBJECT {
            get {
                return ResourceManager.GetString("COD_NULL_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to EXC_OUT_OF_RANGE.
        /// </summary>
        public static string COD_OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("COD_OUT_OF_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to EXC_STRING_NULL_OR_EMPTY.
        /// </summary>
        public static string COD_STRING_NULL_OR_EMPTY {
            get {
                return ResourceManager.GetString("COD_STRING_NULL_OR_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to EXC_UNSUPPORTED_GENERICS_TYPE.
        /// </summary>
        public static string COD_UNSUPPORTED_GENERICS_TYPE {
            get {
                return ResourceManager.GetString("COD_UNSUPPORTED_GENERICS_TYPE", resourceCulture);
            }
        }
    }
}
