//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template.CrossCutting.Resources.ExtensionMethods {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Messages() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrossCutting.Resources.ExtensionMethods.Messages", typeof(Messages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A lista de objetos &apos;{0}&apos; não pode estar vazia..
        /// </summary>
        public static string EXC_EMPTY_LIST {
            get {
                return ResourceManager.GetString("EXC_EMPTY_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to O objeto ou expressão não pode ter valor falso..
        /// </summary>
        public static string EXC_FALSE_VALUE {
            get {
                return ResourceManager.GetString("EXC_FALSE_VALUE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A lista de objetos &apos;{0}&apos; contém objetos nulos..
        /// </summary>
        public static string EXC_HAS_NULL_OBJECT {
            get {
                return ResourceManager.GetString("EXC_HAS_NULL_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A lista de objetos &apos;{0}&apos; não pode ser nula ou vazia..
        /// </summary>
        public static string EXC_LIST_NULL_OR_EMPTY {
            get {
                return ResourceManager.GetString("EXC_LIST_NULL_OR_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to O objeto &apos;{0}&apos; deve ser nulo..
        /// </summary>
        public static string EXC_NOT_NULL_OBJECT {
            get {
                return ResourceManager.GetString("EXC_NOT_NULL_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to O objeto &apos;{0}&apos; não pode ser nulo..
        /// </summary>
        public static string EXC_NULL_OBJECT {
            get {
                return ResourceManager.GetString("EXC_NULL_OBJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to O objeto &apos;{0}&apos; está fora do intervalo: min &apos;{1}&apos;; max &apos;{2}&apos;..
        /// </summary>
        public static string EXC_OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("EXC_OUT_OF_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to O texto &apos;{0}&apos; não pode ser nulo ou vazio..
        /// </summary>
        public static string EXC_STRING_NULL_OR_EMPTY {
            get {
                return ResourceManager.GetString("EXC_STRING_NULL_OR_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Tipo genérico &apos;{0}&apos; não suportado..
        /// </summary>
        public static string EXC_UNSUPPORTED_GENERICS_TYPE {
            get {
                return ResourceManager.GetString("EXC_UNSUPPORTED_GENERICS_TYPE", resourceCulture);
            }
        }
    }
}
