//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Template.CrossCutting.Resources.Validations {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Messages() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrossCutting.Resources.Validations.Messages", typeof(Messages).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} já existe..
        /// </summary>
        public static string AlreadyExists {
            get {
                return ResourceManager.GetString("AlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} e {1} não podem ser preenchidos simultaneamente..
        /// </summary>
        public static string CannotBeFilledSimultaneously {
            get {
                return ResourceManager.GetString("CannotBeFilledSimultaneously", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} não pode ser nulo..
        /// </summary>
        public static string CannotBeNull {
            get {
                return ResourceManager.GetString("CannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} não pode ser nulo ou vazio..
        /// </summary>
        public static string CannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("CannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} ou {1} deve ter valor preenchido..
        /// </summary>
        public static string ConditionalFillParameter {
            get {
                return ResourceManager.GetString("ConditionalFillParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} deve ser maior do que {1}..
        /// </summary>
        public static string GreaterThan {
            get {
                return ResourceManager.GetString("GreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} deve ser maior ou igual a {1}..
        /// </summary>
        public static string GreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("GreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} deve ser maior ou igual a zero..
        /// </summary>
        public static string GreaterThanOrEqualToZero {
            get {
                return ResourceManager.GetString("GreaterThanOrEqualToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} deve ser maior do que zero..
        /// </summary>
        public static string GreaterThanZero {
            get {
                return ResourceManager.GetString("GreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} é um valor inválido..
        /// </summary>
        public static string InvalidData {
            get {
                return ResourceManager.GetString("InvalidData", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} deve ser no formato &apos;{1}&apos;..
        /// </summary>
        public static string InvalidDataFormat {
            get {
                return ResourceManager.GetString("InvalidDataFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} é uma data inválida..
        /// </summary>
        public static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} está com formato inválido: &apos;{1}&apos; - &apos;{2}&apos;..
        /// </summary>
        public static string InvalidDateFormat {
            get {
                return ResourceManager.GetString("InvalidDateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} deve conter apenas números inteiros..
        /// </summary>
        public static string InvalidTypeNumber {
            get {
                return ResourceManager.GetString("InvalidTypeNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} é um e-mail inválido..
        /// </summary>
        public static string IsInvalidEmail {
            get {
                return ResourceManager.GetString("IsInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} deve ser menor do que {1}..
        /// </summary>
        public static string LessThan {
            get {
                return ResourceManager.GetString("LessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} deve ser menor ou igual a {1}..
        /// </summary>
        public static string LessThanOrEqualTo {
            get {
                return ResourceManager.GetString("LessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} deve ser menor ou igual a zero..
        /// </summary>
        public static string LessThanOrEqualToZero {
            get {
                return ResourceManager.GetString("LessThanOrEqualToZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} deve ser menor do que zero..
        /// </summary>
        public static string LessThanZero {
            get {
                return ResourceManager.GetString("LessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} contém um e-mail inválido: &apos;{1}&apos;..
        /// </summary>
        public static string ListHaveInvalidEmail {
            get {
                return ResourceManager.GetString("ListHaveInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} deve ser informado..
        /// </summary>
        public static string MustBeInformed {
            get {
                return ResourceManager.GetString("MustBeInformed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} teve ter um tamanho fixo: &apos;{1}&apos;..
        /// </summary>
        public static string MustHaveFixedSize {
            get {
                return ResourceManager.GetString("MustHaveFixedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} está fora do intervalo: mínimo = &apos;{1}&apos; e máximo = &apos;{2}&apos;..
        /// </summary>
        public static string OutOfRange {
            get {
                return ResourceManager.GetString("OutOfRange", resourceCulture);
            }
        }
    }
}
